# Generated by Django 3.2 on 2022-06-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220629_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('B', 'birthday'), ('R', 'remind')], max_length=150),
        ),
    ]
